# -*- coding: utf-8 -*-
"""Covid_19_prediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-vi73DRmRzPppVE-ye4VJUb4bGtFZZyg
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("/covid_19_clean_complete.csv")

data

data.head(10)

data.columns

data.tail()

data.describe()

data.isnull()

data.isnull().sum()

data.columns

sns.relplot(x="Deaths",y="Confirmed",data = data)

sns.relplot(x="Province/State",y="Confirmed",data = data)

sns.relplot(x="Country/Region",y="Confirmed",data = data)

sns.relplot(x="Confirmed",y="Recovered",data = data)

sns.relplot(x="Confirmed",y="Deaths",data = data)

sns.relplot(x="Confirmed",y="Active",data = data)

sns.relplot(x="WHO Region",y="Confirmed",data = data)

sns.relplot(x="WHO Region",y="Active",data = data)

sns.relplot(x="WHO Region",y="Deaths",data = data)

sns.relplot(x="Confirmed",y="Active",hue = "Deaths" ,data = data)

data.columns

sns.pairplot(data)

sns.relplot(x="Confirmed", y = "Active", kind = "line", data=data)

sns.relplot(x="Confirmed", y = "Deaths", kind = "line", data=data)

sns.relplot(x="Confirmed", y = "Recovered", kind = "line", data=data)

sns.catplot(x="Recovered", y="Active", data=data)